### ISSUE TITLE
Support Ruby 2.4

### ISSUE THREAD

**Issue by cjcolvar** [samvera-labs/samvera-persona#1]
https://github.com/samvera-labs/samvera-persona/blob/bac96bf2d2d1eeb9fff715667acef85fd10e3790/lib/samvera-persona/engine.rb#L15

It looks like `Pathname.glob` was added in ruby 2.5.  We'd like to use persona and would like to continue to support ruby 2.4 until it is EOL'd.  Maybe this could be rewritten for now into the not as nice:
```
app.root.join('db/migrate').children.none? {|path| path.fnmatch?("*.samvera_persona.rb")}
```

**Comment by orangewolf** [comment]
No problem @cjcolvar. I just grabbed join.glob because it worked, not because I'm married to that pattern. Thank you for catching this as we just added the same "have it both ways" code to a couple other engines as well. I'll get a PR up for this in a few minutes

**Comment by cjcolvar** [comment]
Thanks! 🥇
